version: '3'

services:
  app:
    build: ./app
    ports:
      - "3000:3000"

  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app